# -*- coding: utf-8 -*-
"""app

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YshZ0vTLJq1lwolpQ2IM26F1TUqQ607-
"""

import streamlit as st
import pandas as pd
import numpy as np
import tensorflow as tf
import matplotlib.pyplot as plt
import matplotlib.dates as mdates
from sklearn.preprocessing import MinMaxScaler
import time

# 1. PAGE CONFIGURATION
st.set_page_config(
    page_title="High Fidelity PV Forecasting",
    page_icon="☀️",
    layout="wide"
)

# --- CUSTOM CSS FOR SOPHISTICATION ---
st.markdown("""
    <style>
    .main { background-color: #f5f7f9; }
    .stMetric { background-color: #ffffff; padding: 15px; border-radius: 10px; box-shadow: 0 2px 4px rgba(0,0,0,0.05); }
    .stPlotlyChart { border-radius: 10px; overflow: hidden; }
    </style>
    """, unsafe_allow_html=True)

# 2. CACHED MODEL LOADING
@st.cache_resource
def load_prediction_engine():
    try:
        model = tf.saved_model.load("TFLm0_model")
        return model.signatures["serving_default"]
    except Exception as e:
        st.error(f"Error loading model: {e}")
        return None

infer = load_prediction_engine()

# 3. PREPROCESSING PIPELINE (Your Original Logic)
def preprocess_data(df):
    df['date'] = pd.to_datetime(df['date'])
    df.set_index('date', inplace=True)

    # Feature Engineering
    df['Hour'] = df.index.hour
    df['Day'] = df.index.day
    df['Weekday'] = df.index.weekday
    df['Month'] = df.index.month
    df['Year'] = df.index.year

    # Cyclical Encoding
    df['Hour_Sin'] = np.sin(2 * np.pi * df['Hour'] / 24)
    df['Hour_Cos'] = np.cos(2 * np.pi * df['Hour'] / 24)
    df['Day_Sin'] = np.sin(2 * np.pi * df['Day'] / 31)
    df['Day_Cos'] = np.cos(2 * np.pi * df['Day'] / 31)
    df['Weekday_Sin'] = np.sin(2 * np.pi * df['Weekday'] / 7)
    df['Weekday_Cos'] = np.cos(2 * np.pi * df['Weekday'] / 7)
    df['Month_Sin'] = np.sin(2 * np.pi * df['Month'] / 12)
    df['Month_Cos'] = np.cos(2 * np.pi * df['Month'] / 12)

    def get_season(month):
        if month in [12, 1, 2]: return 'Winter'
        elif month in [3, 4, 5]: return 'Spring'
        elif month in [6, 7, 8]: return 'Summer'
        else: return 'Fall'

    df['Season'] = df['Month'].apply(get_season)
    season_dummies = pd.get_dummies(df['Season'], prefix='Season')
    df = pd.concat([df, season_dummies], axis=1)

    for season in ['Season_Winter', 'Season_Spring', 'Season_Summer', 'Season_Fall']:
        if season not in df.columns: df[season] = 0

    df['temp_lag_1'] = df['Temperature at 2M'].shift(1)
    df['wind_lag_1'] = df['Wind Direction at 10 M'].shift(1)
    df['solar_lag_1'] = df['Solar Irradiance'].shift(1)

    df = df.fillna(0)
    df.drop(columns=['Season'], inplace=True)

    X = df.values.astype('float32')
    scaler_X = MinMaxScaler()
    X_scaled = scaler_X.fit_transform(X)
    X_scaled = X_scaled.reshape((X_scaled.shape[0], 1, X_scaled.shape[1]))

    return X_scaled, df.index

# 4. SIDEBAR & BRANDING
with st.sidebar:
    st.image('ss.jpg', use_column_width=True)
    st.title("Settings")
    st.info("Bi-LSTM/Informer Framework v2.1")

    # Seasonal Adjustment Scales
    with st.expander("Adjustment Scales"):
        winter_scale = st.number_input('Winter', value=6.0)
        spring_scale = st.number_input('Spring', value=20.0)
        summer_scale = st.number_input('Summer', value=16.346)
        fall_scale = st.number_input('Fall', value=8.334)

# 5. MAIN HEADER
st.title("⚡ PV GENERATION ANALYTICS")
st.markdown("#### High-Fidelity Bi-LSTM/Informer Framework")

# 6. DATA LOADING & INPUTS
@st.cache_data
def load_dataset():
    return pd.read_csv('Weather historical 01_01_2023 to 31_12_2023.csv')

raw_df = load_dataset()
data_min_date = pd.to_datetime(raw_df['date'].min())
data_max_date = pd.to_datetime(raw_df['date'].max())

col1, col2 = st.columns(2)
with col1:
    start_date = st.date_input('Start date', value=data_min_date)
    start_time = st.time_input('Start time', value=pd.to_datetime('2023-01-01 00:00').time())
with col2:
    end_date = st.date_input('End date', value=data_min_date + pd.Timedelta(days=7))
    end_time = st.time_input('End time', value=pd.to_datetime('2023-01-01 23:00').time())

start_datetime = pd.to_datetime(f"{start_date} {start_time}")
end_datetime = pd.to_datetime(f"{end_date} {end_time}")

# 7. EXECUTION PIPELINE
if start_datetime < data_min_date or end_datetime > data_max_date:
    st.error(f"Please select a range between {data_min_date.date()} and {data_max_date.date()}.")
else:
    if st.button('🚀 Process Prediction', use_container_width=True):
        with st.spinner('Synchronizing Data and Inference Engine...'):
            working_df = raw_df.copy()
            working_df['date'] = pd.to_datetime(working_df['date'])
            filtered_df = working_df[(working_df['date'] >= start_datetime) & (working_df['date'] <= end_datetime)]

            if filtered_df.empty:
                st.warning("No data found for the selected range.")
            else:
                # 7a. Inference
                X_scaled, datetime_index = preprocess_data(filtered_df)
                inputs = tf.convert_to_tensor(X_scaled, dtype=tf.float32)
                predictions = infer(inputs)['output_0'].numpy()

                if predictions.size > 0:
                    predictions = predictions.reshape(-1, 1)

                    # 7b. Dynamic Seasonal Adjustment
                    m = start_datetime.month
                    if m in [12, 1, 2]: adj = winter_scale
                    elif m in [3, 4, 5]: adj = spring_scale
                    elif m in [6, 7, 8]: adj = summer_scale
                    else: adj = fall_scale

                    predictions_adjusted = predictions * adj

                    # 7c. Inverse Scaling (Original Logic)
                    historical_yield_data = np.random.rand(len(predictions_adjusted), 1)
                    scaler_y = MinMaxScaler()
                    scaler_y.fit(historical_yield_data)
                    predictions_inverse = scaler_y.inverse_transform(predictions_adjusted)

                    predictions_df = pd.DataFrame(predictions_inverse, index=datetime_index, columns=['Yield'])

                    # --- VISUALS ---
                    # 1. Metric Overview
                    m1, m2, m3 = st.columns(3)
                    m1.metric("Peak Generation", f"{predictions_df['Yield'].max():.2f} kWh")
                    m2.metric("Total Energy", f"{predictions_df['Yield'].sum():.2f} kWh")
                    m3.metric("Average Yield", f"{predictions_df['Yield'].mean():.2f} kWh")

                    # 2. Main Plot
                    st.divider()
                    fig, ax = plt.subplots(figsize=(15, 6), facecolor='#f5f7f9')
                    ax.plot(predictions_df.index, predictions_df['Yield'], color='#1f77b4', linewidth=2, label='Predicted Output')
                    ax.fill_between(predictions_df.index, predictions_df['Yield'], alpha=0.1, color='#1f77b4')

                    ax.set_ylabel('Generation [kWh]', fontweight='bold')
                    ax.set_title('Short-Term Photovoltaic Yield Forecast', fontsize=14, fontweight='bold')
                    ax.grid(True, linestyle='--', alpha=0.7)
                    ax.xaxis.set_major_formatter(mdates.DateFormatter('%b %d, %H:%M'))
                    plt.xticks(rotation=45)
                    st.pyplot(fig)

                    # 3. Data View & Export
                    with st.expander("🔍 View Raw Forecast Table"):
                        st.dataframe(predictions_df, use_container_width=True)

                    csv = predictions_df.to_csv().encode('utf-8')
                    st.download_button("📥 Download Analysis (CSV)", csv, "pv_forecast.csv", "text/csv")
                else:
                    st.error("Model returned empty results.")