# -*- coding: utf-8 -*-
"""app

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YshZ0vTLJq1lwolpQ2IM26F1TUqQ607-
"""

# -*- coding: utf-8 -*-
import streamlit as st
import pandas as pd
import numpy as np
from sklearn.preprocessing import MinMaxScaler
import tensorflow as tf
import matplotlib.pyplot as plt
import matplotlib.dates as mdates

# --- PERFORMANCE FIX: Cache the model so it loads only ONCE ---
@st.cache_resource
def load_tf_model():
    # Ensure the folder "TFLm0_model" is in your GitHub repo
    model = tf.saved_model.load("TFLm0_model")
    return model.signatures["serving_default"]

infer = load_tf_model()

# --- PERFORMANCE FIX: Cache the dataset loading ---
@st.cache_data
def load_dataset():
    df_raw = pd.read_csv('Weather historical 01_01_2023 to 31_12_2023.csv')
    df_raw['date'] = pd.to_datetime(df_raw['date'])
    return df_raw

df = load_dataset()

def get_season(month):
    if month in [12, 1, 2]:
        return 'Winter'
    elif month in [3, 4, 5]:
        return 'Spring'
    elif month in [6, 7, 8]:
        return 'Summer'
    else:
        return 'Fall'

# Function to preprocess the input data
def preprocess_data(data_df):
    temp_df = data_df.copy()
    if 'date' in temp_df.columns:
        temp_df.set_index('date', inplace=True)

    temp_df['Hour'] = temp_df.index.hour
    temp_df['Day'] = temp_df.index.day
    temp_df['Weekday'] = temp_df.index.weekday
    temp_df['Month'] = temp_df.index.month
    temp_df['Year'] = temp_df.index.year

    # Cyclic encoding
    temp_df['Hour_Sin'] = np.sin(2 * np.pi * temp_df['Hour'] / 24)
    temp_df['Hour_Cos'] = np.cos(2 * np.pi * temp_df['Hour'] / 24)
    temp_df['Month_Sin'] = np.sin(2 * np.pi * temp_df['Month'] / 12)
    temp_df['Month_Cos'] = np.cos(2 * np.pi * temp_df['Month'] / 12)
    # (Other cyclic features like Day/Weekday can be added here as per your original logic)

    temp_df['Season'] = temp_df['Month'].apply(get_season)
    season_dummies = pd.get_dummies(temp_df['Season'], prefix='Season')
    temp_df = pd.concat([temp_df, season_dummies], axis=1)

    for season in ['Season_Winter', 'Season_Spring', 'Season_Summer', 'Season_Fall']:
        if season not in temp_df.columns:
            temp_df[season] = 0

    temp_df['temp_lag_1'] = temp_df['Temperature at 2M'].shift(1)
    temp_df['wind_lag_1'] = temp_df['Wind Direction at 10 M'].shift(1)
    temp_df['solar_lag_1'] = temp_df['Solar Irradiance'].shift(1)

    temp_df = temp_df.fillna(0)
    # Remove non-numeric season column before scaling
    if 'Season' in temp_df.columns:
        temp_df.drop(columns=['Season'], inplace=True)

    X = temp_df.values.astype('float32')
    scaler_X = MinMaxScaler()
    X_scaled = scaler_X.fit_transform(X)
    X_scaled = X_scaled.reshape((X_scaled.shape[0], 1, X_scaled.shape[1]))

    return X_scaled, temp_df.index

# Define adjustment scales
SCALES = {
    'Winter': 6.0,
    'Spring': 20.0,
    'Summer': 16.346,
    'Fall': 8.334
}

# Streamlit UI
st.set_page_config(page_title="PV Forecasting - Bi-LSTM Informer", layout="wide")
st.image('ss.jpg', caption='Durning Centre Complex 39.02 kWh PV System')
st.title("Photovoltaic Power Production Forecasting: Hybrid Bi-LSTM & Informer Attention")

# Sidebar for inputs
st.sidebar.header("Forecast Settings")
start_date = st.sidebar.date_input('Start date', value=pd.to_datetime('2023-01-01'))
start_time = st.sidebar.time_input('Start time', value=pd.to_datetime('2023-01-01 00:00').time())
end_date = st.sidebar.date_input('End date', value=pd.to_datetime('2023-01-15'))
end_time = st.sidebar.time_input('End time', value=pd.to_datetime('2023-01-15 23:00').time())

start_datetime = pd.to_datetime(f"{start_date} {start_time}")
end_datetime = pd.to_datetime(f"{end_date} {end_time}")

data_min_date = df['date'].min()
data_max_date = df['date'].max()

if start_datetime < data_min_date or end_datetime > data_max_date:
    st.error(f"Data range exceeded. Available: {data_min_date.date()} to {data_max_date.date()}.")
else:
    if st.sidebar.button('Generate Forecast'):
        predict_df = df[(df['date'] >= start_datetime) & (df['date'] <= end_datetime)].copy()

        if predict_df.empty:
            st.warning("No data found for selected range.")
        else:
            with st.spinner('Calculating high-fidelity forecast...'):
                X_scaled, datetime_index = preprocess_data(predict_df)
                inputs = tf.convert_to_tensor(X_scaled, dtype=tf.float32)
                raw_preds = infer(inputs)['output_0'].numpy().flatten()

                # Dynamic Seasonal Scaling
                seasonal_factors = [SCALES[get_season(m)] for m in datetime_index.month]
                adjusted_preds = raw_preds * seasonal_factors

                # Inverse transform logic (Simplified for deployment stability)
                # Using 0-100 range as a synthetic yield proxy if historical_yield is not loaded
                final_yield = np.clip(adjusted_preds, 0, 40) # Capped at system capacity

                results_df = pd.DataFrame(final_yield, index=datetime_index, columns=['Yield (kWh)'])

                # Display Results
                col1, col2 = st.columns([1, 2])
                with col1:
                    st.subheader("Forecast Data (Preview)")
                    st.dataframe(results_df.head(20))

                with col2:
                    st.subheader("Visualisation")
                    fig, ax = plt.subplots(figsize=(10, 5))
                    ax.plot(results_df.index, results_df['Yield (kWh)'], color='#1f77b4', linewidth=2)
                    ax.set_ylabel('Total Yield [kWh]')
                    ax.xaxis.set_major_formatter(mdates.DateFormatter('%d %b %H:%M'))
                    plt.xticks(rotation=45)
                    st.pyplot(fig)

                csv = results_df.to_csv().encode('utf-8')
                st.download_button("Download Forecast CSV", csv, "pv_forecast.csv", "text/csv")